[dataset]
file_path = "./data/battery-failure-databank.xlsx"
sheet_name = "Battery Failure Databank"
na_values = "-"
input_cols = [
  "Cell-Description"
  ,"Cell-Format"
  ,"Cell-Capacity-Ah"
  ,"Cell-Nominal-Voltage-V"
  ,"Cell-Energy-Wh"
  ,"Trigger-Mechanism"
  ,"Cell-Failure-Mechanism"
  ,"Pre-Test-Cell-Open-Circuit-Voltage-V"
  ,"Pre-Test-Cell-Mass-g"
  ,"Pre-Test-Positive-Copper-Mesh-Mass-g"
  ,"Pre-Test-Negative-Copper-Mesh-Mass-g"
  ,"Pressure-Assisted-Seal-Configuration-Positive"
  ,"Pressure-Assisted-Seal-Configuration-Negative"
]
output_cols = [
    "Energy-Fraction-Cell-Body-kJ"
    ,"Energy-Fraction-Positive-Ejecta-kJ"
    ,"Energy-Fraction-Negative-Ejecta-kJ"
]
stratify_col = "Cell-Failure-Mechanism"
test_size = 0.3
random_state = 42

[cross_validation]
n_splits = 5
n_repeats = 10
random_state = 100

[grid_search]
scoring = "neg_mean_squared_error"

[linear_regression]
fit_intercept = [true, false]
n_jobs = [1, 5]
positive = [true, false]

[random_forest]
n_estimators = [100, 200]
max_features = ["sqrt", "log2"]
max_depth = [3, 5, 8]

[metrics]
multioutput_method = "raw_values" # ["raw_values", "uniform_average"]
