[dataset]
file_path = "./data/battery-failure-databank.xlsx"
sheet_name = "Battery Failure Databank"
na_values = "-"
input_cols = [
  "Cell-Description"
  # ,"Cell-Format"
  ,"Cell-Capacity-Ah"
  ,"Cell-Nominal-Voltage-V"
  ,"Cell-Energy-Wh"
  ,"Trigger-Mechanism"
  ,"Pre-Test-Cell-Open-Circuit-Voltage-V"
  ,"Pre-Test-Cell-Mass-g"
  ,"Pressure-Assisted-Seal-Configuration-Positive"
  ,"Pressure-Assisted-Seal-Configuration-Negative"
  ,"Bottom-Vent-Yes-No"
]
output_cols = [
    "Energy-Fraction-Cell-Body-kJ"
    ,"Energy-Fraction-Positive-Ejecta-kJ"
    ,"Energy-Fraction-Negative-Ejecta-kJ"
    ,"Post-Test-Mass-Unrecovered-g"
]
stratify_col = "Trigger-Mechanism"
test_size = 0.3
random_state = 42

[feature_selection]
corr_threshold = 0.85
authors = [
  "Cell-Capacity-Ah"
  ,"Pre-Test-Cell-Mass-g"
  ,"State-of-Charge"
  ,"Chemistry_NMC/Graphite"
  ,"Trigger-Mechanism_Nail"
  ,"Bottom-Vent-Yes-No"
]

[cross_validation]
n_splits = 5
n_repeats = 10
random_state = 100

[grid_search]
scoring = "neg_mean_squared_error"

[ridge_regression]
alpha = [0.1, 1.0, 10.0, 100.0]
fit_intercept = [true, false]
max_iter = [100, 500, 1000]

[random_forest]
n_estimators = [100, 200]
max_features = ["sqrt", "log2"]
max_depth = [3, 5, 8]

[mlp]
hidden_layer_sizes = [[20], [20, 10], [50, 25], [60, 30, 15]]
activation = ["relu"]
solver = ["adam", "sgd"]
learning_rate = ["constant", "adaptive"]
max_iter = [1000, 5000]

[metrics]
multioutput_method = "uniform_average" # ["raw_values", "uniform_average"]
figure_name = "./results/figures/{plot}/{config}.pdf"
